apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ipablo
spec:
  profile:
    displayName: Pablo Iglesias
    email: ipablo@vmware.com
    picture: https://api.dicebear.com/6.x/avataaars-neutral/svg?seed=Boo
  memberOf: [team-a]
